### ISSUE TITLE
Automatically adjust the screen brightness to save battery.

### ISSUE THREAD

**Issue by Aniq55** [rricharz/pi-top-install#10]
Decrease brightness with decreasing battery charge.

suppose, the user has already set the brightness to a level, say `brightness_max_user`
and the battery charge remaining in P%. we map `(brightness_max_user , brightness_min)` to `(P, 10)` and decrease the brightness step by step as the battery drains.

**Comment by rricharz** [comment]
I will look into this. There are several ways how this could be implemented. Are you using Raspian or pi-topOS? Do you have pi-top-battery-status (gtk_battery) installed? It would be easy to put it into that program.

**Comment by rricharz** [comment]
I am not going to implement this to keep pi-top-install as simple as possible.
