### ISSUE TITLE
Interface a 16x02 character LCD to display pop-up notifications

### ISSUE THREAD

**Issue by Aniq55** [rricharz/pi-top-install#11]
Show pop-up notifications on the 16x02 LCD display, instead of using the screen.
If a mail is received, the LCD will display the name of the sender and the subject of the mail.
If I am playing a song on the device, the name of the song and the artist will be displayed on the LCD.
and other such applications.

**Comment by rricharz** [comment]
You can probably use something like [displayotron](https://github.com/pimoroni/dot3k) on the pi-topPROTO. I'm not sure however whether it is fully compatible with the pi-top hardware. Both use the spi and i2c bus.

**Comment by Aniq55** [comment]
@rricharz thanks. (:
