### ISSUE TITLE
Pi top can not be turned on again after power off installed

### ISSUE THREAD

**Issue by wlaws** [rricharz/pi-top-install#12]
I want to use Raspbian Jessie with pixel on a Pi-top.  I downloaded the March 2017 Jessie image on to a SD card and because it no longer has any pi-top os I have to manually power off the pi-top.
I came across your code, installed this part:-
In terminal:

`sudo apt-get install wiringpi
cd Downloads
git clone git://github.com/rricharz/pi-top-install
cd pi-top-install
chmod +x install*`

I enable spi in Menu->Preferences->Raspberry Pi Configuration->Interfaces.

In terminal:

`sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
./install-poweroff
`

then when I choose shutdown from the shutdown menu I can't restart the pi-top (Reboot is ok).  Only by disconnecting the battery, reconnecting again will it start.  Where have I gone wrong?

**Comment by rricharz** [comment]
`As` far as I can see you have done everything right.

Install brightness control and check whether it works. That will tell us whether the pi-top can talk properly to the hub-controller. If that does not work right, you need the check the 40 pin cable.

Then, install pi-top-battery-status. Does the battery work fine? Does it charge and discharge properly?

If that does not solve the problem,  go the the pi-top-install directory and type
`.\uninstall-poweroff`

Shutdown the rpi with the menu. The red light should stay on. Press the on/off button for a few seconds. The red light should go off. Can you now turn the pi-top on again with the button?

Now, go back to the pi-top-install directory. Install poweroff with
`.\install-poweroff`

Shutdown the rpi with the menu. At the end of the shutdown, the yellow light will blink a few times, then after a few seconds the red light will turn off. Can you now turn the pi-top on again with the button? If still not, I believe that you have a strange hardware problem.

**Comment by rricharz** [comment]
Any news on this issue?

**Comment by rricharz** [comment]
Closed because issue not reported by any other user
