### ISSUE TITLE
Your battery, backlight and poweroff utils in a bootable 64-bit Gentoo image for the Pi-Top

### ISSUE THREAD

**Issue by sakaki-** [rricharz/pi-top-install#17]
Hi,

just a quick note to thank you for your work on the Pi-Top. I maintain a bootable 64-bit Gentoo image for the RPi3, and have just released a variant supporting the Pi-Top (see [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit)).

In the variant image, I have used your code for `pt-poweroff` and `pt-brightness` (using a 64-bit build of `wiringpi`), and have merged your I2C battery code as a library into the `xfce4-battery-plugin`. You can see the various ebuilds, patches etc in the [rpi3-overlay](https://github.com/sakaki-/rpi3-overlay) which the image uses.

Your notes on the pitopSPEAKER were also very useful (I have included a driver for that on the image too, which does not use the pt-peripherals-daemon).

I've cited you as 'upstream' in the various ebuild metadata, hope that's OK.

Well, if you get a chance to try the 64-bit image on your Pi-Top, please let me know of any issues you encounter! (It's just a question of downloading, burning and booting, goes straight to an Xfce4 desktop, there's nothing to configure just to play with it).

Best, sakaki

**Comment by rricharz** [comment]
Many thanks for this interesting information. I will certainly try the Gentoo image on my pi-top. If it works well, I will add a link in the readme.md file.

**Comment by rricharz** [comment]
I have added a link to the Gentoo image at the bottom of the readme.md file.

**Comment by m-roberts** [comment]
@sakaki- 

Hi, my name is Mike and I am one of the lead developers for pi-topOS. We would be very interested in talking to you about your Gentoo build, and how we can make it easier for you to maintain your pi-top support - preferably by making the 'official' software as easy as possible for you to integrate.

Please drop me a line at mike@pi-top.com so that I can begin to understand what your requirements might be, and how we can work together to improve the software support for interacting with the pi-top hardware.

**Comment by sakaki-** [comment]
Many thanks for the link!

BTW, I've tried (a few times) posting an announcement about the image into the Pi-Top community forums, but unfortunately the message seems to get automoderated to `/dev/null` each time, they must have a pretty aggressive spam filter active on there ><

**Comment by rricharz** [comment]
Yes, the forum seems to reject anything containing a link and most things containing other formatting. I got around this by just having xyz.com instead of http://xyz.com in my forum contributions. But of course this means that the users have to copy paste the link into their browser.
