### ISSUE TITLE
update to latest raspbian with pixel desktop disables autostart of pt-speaker

### ISSUE THREAD

**Issue by tvoverbeek** [rricharz/pi-top-install#6]
Note that when updating/upgrading to the latest Raspbian with Pixel desktop the pt-speaker entry (@pt-speaker) disappears since the desktop autostart file gets replaced. After adding it manually it works again.

**Comment by rricharz** [comment]
Many thanks, I did not notice this up to now. Unfortunately the manual installation of Pixel overwrites a number of configuration files. I have added instructions at the bottom of speaker.txt to resolve this issue.
