### ISSUE TITLE
Brightness ramps up to max by itself

### ISSUE THREAD

**Issue by JezShed** [rricharz/pi-top-install#7]
After performing a dist-upgrade to "Pixel" on my pi-top, I re-installed all the pi-top things using your install process. Although the brightness keys do work, the brightness ramps up to maximum again without pressing any keys. I've also re-installed your excellent battery gauge and that works perfectly.

Everything else seems to work correctly.

Any thoughts Richard?

All the best,
Jez

PS. I've tried uninstalling brightness and re-installing it but the strange problem remains.

UPDATE: I disabled SPI, re-enabled SPI and the brightness keys now work perfectly :)

**Comment by rricharz** [comment]
Thanks Jez,
Please report of you see the problem again. 

This could possibly happen if my brightness program is installed by mistake in pi-topOS. The battery monitor works in Raspbian and pi-topOS, but my brightness and shutdown programs are only for Raspian Jessie. 

If you do a
  ps -aux | grep hub-controller

and see that a hub-controller process is running in background, you have started with pi-topOS. In that case you would have to start over with a new image of pi-topOS or Raspbian Jessie, whichever you prefer.
