### ISSUE TITLE
gig.key file has invalid filename extension!

### ISSUE THREAD

**Issue by dpenney5** [rricharz/pi-top-install#9]
Hi,
I have followed your instructions but now get an error saying the key file has an incorrect extension.
What is wrong? I have put the log below - the error is at the end & reads:
"N: Ignoring file 'apt.pi-top.com.gpg.key' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension".
the wget command needs to have a sudo in front in order to execute.
Thanks
best regards
David
-------------
pi@cal2:/etc/apt/sources.list.d $ sudo -E wget http://apt.pi-top.com/apt.pi-top.com.gpg.key
--2016-11-27 02:12:05--  http://apt.pi-top.com/apt.pi-top.com.gpg.key
Resolving apt.pi-top.com (apt.pi-top.com)... 104.28.31.253, 104.28.30.253, 2400:cb00:2048:1::681c:1ffd, ...
Connecting to apt.pi-top.com (apt.pi-top.com)|104.28.31.253|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4082 (4.0K) [application/octet-stream]
Saving to: ‘apt.pi-top.com.gpg.key’

apt.pi-top.com.gpg. 100%[=====================>]   3.99K  --.-KB/s   in 0s     

2016-11-27 02:12:05 (35.8 MB/s) - ‘apt.pi-top.com.gpg.key’ saved [4082/4082]

pi@cal2:/etc/apt/sources.list.d $ sudo apt-key add apt.pi-top.com.gpg.key
OK
pi@cal2:/etc/apt/sources.list.d $ sudo apt-get update
Hit http://mirrordirector.raspbian.org jessie InRelease                        
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages              
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages           
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages          
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages               
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB        
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en           
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB           
Ign http://mirrordirector.raspbian.org jessie/main Translation-en              
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB       
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en          
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB            
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en               
Hit http://apt.pi-top.com jessie InRelease                                     
Hit http://apt.pi-top.com jessie/main armhf Packages                           
Hit http://archive.raspberrypi.org jessie InRelease                            
Hit http://archive.raspberrypi.org jessie/main armhf Packages                  
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Ign http://apt.pi-top.com jessie/main Translation-en_GB
Ign http://apt.pi-top.com jessie/main Translation-en
Reading package lists... Done
N: Ignoring file 'apt.pi-top.com.gpg.key' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
pi@cal2:/etc/apt/sources.list.d $

**Comment by rricharz** [comment]
Hi,
It is difficult to see what exactly went wrong in your case. Check the file "pi-top.list" which you made in "/etc/apt/sources.list.d". It should contain one line:
  deb http://apt.pi-top.com/raspbian/ jessie main
(with a space before and after jessie!)
You might have to delete 'apt.pi-top.com.gpg.key' in '/etc/apt/sources.list.d/' and repeat the procedure.

**Comment by dpenney5** [comment]
Hi
The instructions need another step.
sudo rm apt.pi-top.com.gpg.key
To delete the key file before doing a sudo apt-get update

Also the line wget should have sudo in front of it

Now it is working - thanks for your quick response - much appreciated.

Best regards,
                David
---------------------

**Comment by rricharz** [comment]
Many thanks. Your input is very much appreciated. I have updated the instructions using the home directory as a temporary storage position for the gpk.key file (sudo not needed for wget and rm)
